symbols:
  [
    "BTCUSD",
    "ETHUSD",
    "BCHUSD",
    "XRPUSD",
    "LTCUSD",
    "TRXUSD",
    "ETCUSD",
    "LINKUSD",
    "XLMUSD",
    "ADAUSD",
    "XMRUSD",
    "DASHUSD",
    "ZECUSD",
    "XTZUSD",
    "BNBUSD",
    "ATOMUSD",
    "ONTUSD",
    "IOTAUSD",
    "BATUSD",
    "VETUSD",
    "NEOUSD",
    "QTUMUSD",
    "IOSTUSD",
    "THETAUSD",
    "ALGOUSD",
    "ZILUSD",
    "KNCUSD",
    "ZRXUSD",
    "COMPUSD",
    "PENDLEUSD",
    "DOGEUSD",
    "SXPUSD",
    "KAVAUSD",
    "BANDUSD",
    "RLCUSD",
    "ORDIUSD",
    "MKRUSD",
    "SNXUSD",
    "DOTUSD",
    "PIXELUSD",
    "YFIUSD",
    "ARKMUSD",
    "CRVUSD",
    "TRBUSD",
    "RUNEUSD",
    "SUSHIUSD",
    "EGLDUSD",
    "SOLUSD",
    "ICXUSD",
    "STORJUSD",
    "TIAUSD",
    "UNIUSD",
    "AVAXUSD",
    "GMXUSD",
    "ENJUSD",
    "FLMUSD",
    "DYDXUSD",
    "KSMUSD",
    "NEARUSD",
    "AAVEUSD",
    "FILUSD",
    "RSRUSD",
    "LRCUSD",
    "WLDUSD",
    "BELUSD",
    "AXSUSD",
    "ALPHAUSD",
    "ZENUSD",
    "SKLUSD",
    "GRTUSD",
    "1INCHUSD",
    "CHZUSD",
    "SANDUSD",
    "ANKRUSD",
    "SUIUSD",
    "SEIUSD",
    "APEUSD",
    "RVNUSD",
    "SFPUSD",
    "1000CHEEMSUSD",
    "LDOUSD",
    "COTIUSD",
    "CHRUSD",
    "MANAUSD",
    "ALICEUSD",
    "HBARUSD",
    "ONEUSD",
    "APTUSD",
    "INJUSD",
    "DENTUSD",
    "CELRUSD",
    "HOTUSD",
    "MTLUSD",
    "OGNUSD",
    "NKNUSD",
    "OPUSD",
    "ARBUSD",
    "1000SHIBUSD",
    "BAKEUSD",
    "GTCUSD",
  ]
day: 1
pattern: "https://data.binance.vision/data/futures/{market}/daily/trades/{symbol}/{symbol}-trades-{d}.zip"
output_path: "src/downloader/urls_list.json"
market: "um"
